name: CMake

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Clone OpenCL-Headers
        run: git clone https://github.com/KhronosGroup/OpenCL-Headers

      - name: Clone ICD loader
        run: git clone https://github.com/KhronosGroup/OpenCL-ICD-Loader

      - name: Configure ICD Loader
        run: cp -r ${{github.workspace}}/OpenCL-Headers/CL ${{github.workspace}}/OpenCL-ICD-Loader/inc &&
             cmake -H${{github.workspace}}/OpenCL-ICD-Loader -B ${{github.workspace}}/OpenCL-ICD-Loader/build

      - name: Build ICD Loader
        run: cmake --build ${{github.workspace}}/OpenCL-ICD-Loader/build --config Release

      - name: Install ICD Loader
        run: cmake --install ${{github.workspace}}/OpenCL-ICD-Loader/build
             --prefix ${{github.workspace}}/OpenCL-ICD-Loader
             --config Release

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -H${{github.workspace}} -B ${{github.workspace}}/build
             -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
             -DCMAKE_LIBRARY_PATH=${{github.workspace}}/OpenCL-ICD-Loader/lib
             -DCMAKE_INCLUDE_PATH=${{github.workspace}}/OpenCL-ICD-Loader/inc

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
